apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: ./charts/metrics-server
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
      version: "5.8.9"
  interval: 1m0s
  install:
    remediation:
      retries: 3