apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: flux-system
      version: "5.8.9"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3