apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: gatekeeper-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml