apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helm-charts
  namespace: flux-system
spec:
  interval: 1m
  url: git@github.com:smills24/flux2-kustomize-helm-example.git